### ISSUE TITLE
 Elasticsearch\Common\Exceptions\NoNodesAvailableException    No alive nodes found in your cluster

### ISSUE THREAD

**Issue by shoaibbrosol** [cviebrock/laravel-elasticsearch#1]
**NOTE:  This Package Will Be Abandoned**
Due to several factors, including the fact that I no longer use ES, 
I will be ceasing development on this package.  Bug fixes with PRs will
eventually be looked at, but requests for new features or general support
questions may go unanswered.

If you are interested in taking over this project, please reach out to 
me here on Github, or on Twitter: @cviebrock

---

Please be sure you include all the relevant information in your issue so we can help you:

- [ ] What steps where taken to reproduce your issue?
- [ ] What are your configuration file(s), where relevant?
- [ ] If it's a problematic ES query, then have you tested it directly
      with the [official PHP client](https://github.com/elastic/elasticsearch-php)?
      Remember, this package is basically just a configuration helper that wraps the
      official client.  If it doesn't work there, then the issue isn't with my package.
- [ ] Is there any other code we might need to see in order to help?

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
Not enough information in your issue comment, plus this package is abandoned. See the README for details. 

That said, the error indicates you don’t have any available ES nodes. Have you tried connecting using the PHP client directly?
